version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - 5432

  myapp:
    build: .
    image: myapp
    command: yarn start
    environment:
      APP_DB_HOST: db
      APP_DB_USER: john
      APP_DB_PASSWORD: mysecretpassword
    expose:
      - 8000
    depends_on:
      - db

  # myapp-tests:
  #   image: myapp
  #   command: dockerize
  #     -wait tcp://db:5432 -wait tcp://myapp:8000 -timeout 10s
  #     bash -c "node db/init.js && yarn test"
  #   environment:
  #     APP_URL: http://myapp:8000
  #     APP_DB_HOST: db
  #     APP_DB_USER: john
  #     APP_DB_PASSWORD: mysecretpassword
  #   depends_on:
  #     - db
  #     - myapp
